[default]
app_name = "blog-app"
version = "0.5.0"
timezone = "Europe/Moscow"
debug = false
log_level = "INFO"


[development]
dynaconf_merge = true
app_env = "development"
debug = true
log_level = "DEBUG"


[production]
app_env = "production"
debug = false
log_level = "WARNING"
