services:
  blog_app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      BLOG_APP_DATABASE__HOST: blog_app_db
    depends_on:
      blog_app_db:
        condition: service_healthy

  blog_app_db:
    image: postgres:18-bookworm
    ports:
      - "${BLOG_APP_DATABASE__PORT}:5432"
    environment:
      POSTGRES_DB: ${BLOG_APP_DATABASE__NAME}
      POSTGRES_USER: ${BLOG_APP_DATABASE__USER}
      POSTGRES_PASSWORD: ${BLOG_APP_DATABASE__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BLOG_APP_DATABASE__USER} -d ${BLOG_APP_DATABASE__NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
